### PR TITLE
repair in plot_results.py for IETS (still not fully working).

### PR DESCRIPTION
**Pull request by ondrejkrejci**
There was one problem in plot_results.py, which is solved with this. Allows to run at least one IETS example, that we have on PPSTM.

The small change in the fastmath_light.h enables easier compilation from source on more platforms (at least it is working for me on my crazy Win machine without sudo).

And I have learned how the new formating and precommit things are working 👍 .

### CODE REVIEW

**Review by NikoOinonen — APPROVED** [review]
LGTM!

**Comment by NikoOinonen** [comment]
@yakutovicha Is it really the case that if you add a single line that is not tested, then it fails the CI test completely? I think this is maybe too strict of a requirement for every PR.

**Comment by yakutovicha** [comment]
> @yakutovicha Is it really the case that if you add a single line that is not tested, then it fails the CI test completely? I think this is maybe too strict of a requirement for every PR.

There should be a setting for that. Sorry, I can't recall exactly how to change it. Feel free to update it.

**Comment by yakutovicha** [comment]
@NikoOinonen, I think I changed the threshold to 2%. Let's hope it will work.

**Pull request merged**
