### PR TITLE
formating

### PR DESCRIPTION
**Pull request by ProkopHapala**
I would remove formating from these sections for now;

I did not go through the code very carefully, maybe there are some other part worth excluding from format.

But I think it is actually easier to reformat them manually later (and put `fmt: on`) than to read the code carefully line-by-line noew

### CODE REVIEW

**Comment by ProkopHapala** [comment]
@yakutovicha  - I did not look into `/dev` folder. Could you **switch off** automatic the formatting for that folder?

**Comment by yakutovicha** [comment]
> @yakutovicha - I did not look into `/dev` folder. Could you **switch off** automatic the formatting for that folder?

I will do that when applying black to the whole repository.

**Comment by yakutovicha** [comment]
@ProkopHapala, before the review, would you be able to resolve the conflicts?

**Comment by ProkopHapala** [comment]
> @ProkopHapala, before the review, would you be able to resolve the conflicts?

OK, I did, but I don't see why there were these conflics

**Comment by yakutovicha** [comment]
> > @ProkopHapala, before the review, would you be able to resolve the conflicts?
> 
> OK, I did, but I don't see why there were these conflics

It's because my PR was merged first, and our changes are a little bit in conflict with each other.

**Review by yakutovicha — APPROVED** [review]
LGTM!

**Pull request merged**
