### PR TITLE
Update the docker container.

### PR DESCRIPTION
**Pull request by yakutovicha**
Slight update of the Dockerfile to be in sync with the latest developments of ppafm.

### CODE REVIEW

**Comment by NikoOinonen** [comment]
I was just testing this on my computer, and got the same `PermissionError: [Errno 13] Permission denied: 'FFLJ_x.xsf` as in the CI test. For me the problem was that the example folder did not have write permission for other users. When I set the `777` permissions, then it worked.

**Comment by yakutovicha** [comment]
> I was just testing this on my computer, and got the same `PermissionError: [Errno 13] Permission denied: 'FFLJ_x.xsf` as in the CI test. For me the problem was that the example folder did not have write permission for other users. When I set the `777` permissions, then it worked.

Yes, I just tried that approach too and added to the test.

**Comment by yakutovicha** [comment]
By the way, @NikoOinonen, do you have a win machine? That would be great if someone could test it on win too.

**Comment by NikoOinonen** [comment]
Sure, I can try on Windows as well.

**Comment by NikoOinonen** [comment]
Also getting that setuptools error now. I have seen this before, when pip for some reason priorities the Ubuntu system setuptools installation which is some ancient version. It can be fixed in a kind of brute force way by removing the default setuptools installation and replacing it like here: https://askubuntu.com/questions/683601/how-to-upgrade-python-setuptools-12-2-on-ubuntu-15-04/683730#683730

**Comment by yakutovicha** [comment]
@NikoOinonen I finally managed to simplify the Docker file and make things work. The PR is ready for your review and testing.

**Comment by yakutovicha** [comment]
Maybe we should test this docker image for different systems as well, what do you think @NikoOinonen?

**Comment by yakutovicha** [comment]
Well, I tried and failed. I don't have too much interest and time to work on this further. Let's review/merge it as it is. We can always add more stuff later.

**Comment by NikoOinonen** [comment]
It seems to work in both Linux and Windows. On Windows the only difference is that in cmd `PWD` does not work, so you run docker with
```bash
docker run --rm -v %CD%:/exec ppafm:latest ...
```
I added a note of that to the [wiki](https://github.com/Probe-Particle/ppafm/wiki/Additional-installation-instructions).

**Review by NikoOinonen — APPROVED** [review]

**Pull request merged**
