### PR TITLE
224 add openmp acceleration

### LINKED ISSUE #224: add OpenMP acceleration?
There is huge discrepancy between speed of GPU and CPU code (>100x), which is a bit unfair because modern multi-core vectorized CPUs are able to provide much higher performance than what we are currently using. 

Adding vectorized version of forcefield evaluation and probe-particle relaxation should be rather staightforward. Although it is a question if there is considerable motivation to do that when we have already super vast OpenCL implementation?

### PR DESCRIPTION
**Pull request by ProkopHapala**
Closes #224 

* I implemented OpenMP paralelization of forcefield gengeration and probe particle relaxation on CPU
* I'm not sure it the dependency on `-fopenmp` in makefile and `#include <omp.h>` does not couase some problems on other platforms ?
* For now I tested it only on Graphene example

### CODE REVIEW

**Comment by yakutovicha** [comment]
@ProkopHapala please merge the main branch into the current one, to make sure the tests are passing.

Also, please enable the [pre-commit](https://github.com/Probe-Particle/ppafm/wiki/For-Developers#enable-pre-commit-hooks).

**Comment by ProkopHapala** [comment]
> @ProkopHapala please merge the main branch into the current one, to make sure the tests are passing.

* But merging should be done only after the PR is accepted or not?
* Also I think I should put there some option (switch, environment variable) to enable run it without OpenMP 

> Also, please enable the [pre-commit](https://github.com/Probe-Particle/ppafm/wiki/For-Developers#enable-pre-commit-hooks).

I' tried, but not sure what is going on, why all tests are skipped?

```
prokop@DesktopGTX3060:~/git/ppafm$ git commit -a -m "try pre-commit"
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/pycqa/isort.
[INFO] Initializing environment for https://github.com/PyCQA/autoflake.
[INFO] Initializing environment for https://github.com/asottile/pyupgrade.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://github.com/jumanjihouse/pre-commit-hook-yamlfmt.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pycqa/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/PyCQA/autoflake.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/asottile/pyupgrade.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/jumanjihouse/pre-commit-hook-yamlfmt.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
fix end of files.....................................(no files to check)Skipped
trim trailing whitespace.............................(no files to check)Skipped
check yaml...........................................(no files to check)Skipped
check for added large files..........................(no files to check)Skipped
isort................................................(no files to check)Skipped
autoflake............................................(no files to check)Skipped
pyupgrade............................................(no files to check)Skipped
black................................................(no files to check)Skipped
Format YAML files....................................(no files to check)Skipped
On branch 224-add-openmp-acceleration
Your branch is up to date with 'origin/224-add-openmp-acceleration'.

nothing to commit, working tree clean
prokop@DesktopGTX3060:~/git/ppafm$ 
```

**Comment by yakutovicha** [comment]
> * But merging should be done only after the PR is accepted or not?

When a PR is merged we say "The current branch is merged into the main branch". To get the current branch up-to-date with `main` we "merge main into the current branch.":

```bash
$ git checkout 224-add-openmp-acceleration
$ git merge main
```

This is what I meant.

> > Also, please enable the [pre-commit](https://github.com/Probe-Particle/ppafm/wiki/For-Developers#enable-pre-commit-hooks).
> 
> I' tried, but not sure what is going on, why all tests are skipped?

What you did is fine, but this only works for the files that were modified in the current commit. As far as I can see your current commit has no changes. The way to apply pre-commit at this point is to run it for the whole repository:

```bash
$ pre-commit run --all-files
```

And then commit the updates files.

**Comment by ProkopHapala** [comment]
> ```shell
> $ pre-commit run --all-files
> ```
> And then commit the updates files.

OK, I did.

It is doing this horrible thing. Can we prevent it?

(adding lines in between definition of ctypes binding of function and its arguments)
```
@@ -284,6 +290,8 @@ def getGaussDensity(Rs, cRAs):
 # void getSlaterDensity( int natoms_, double * Ratoms_, double * cRAs ){
 lib.getSlaterDensity.argtypes = [c_int, array2d, array2d]
 lib.getSlaterDensity.restype = None
+
+
 def getSlaterDensity(Rs, cRAs):
     natom = len(Rs)
     lib.getSlaterDensity(natom, Rs, cRAs)
```

**Comment by yakutovicha** [comment]
> It is doing this horrible thing. Can we prevent it?

As far as I can tell the ways to prevent things are still the same:
1. Add `fmt: off - fmt:on`
2. Do not format this file at all (add it to the ignore section of black).

In that particular case, the best thing IMO is to move everything inside the python function:

```python


+
+
 def getSlaterDensity(Rs, cRAs):
     # void getSlaterDensity( int natoms_, double * Ratoms_, double * cRAs ){
     lib.getSlaterDensity.argtypes = [c_int, array2d, array2d]
     lib.getSlaterDensity.restype = None
     natom = len(Rs)
     lib.getSlaterDensity(natom, Rs, cRAs)
```

**Comment by ProkopHapala** [comment]
@NikoOinonen @yakutovicha 

ad `Some checks were not successful` ... when I look on the details of the unsuccesful test, it seems to be something conected with `OpenCL` and `reikna`, which should be completely orthogonal to the CPU code in C++ I eddited. Isn't this actually symptom of another issue which @NikoOinonen raised some time ago ?

```
Run pytest tests -v --cov
============================= test session starts ==============================
platform linux -- Python 3.9.18, pytest-7.4.3, pluggy-1.3.0 -- /opt/hostedtoolcache/Python/3.9.18/x64/bin/python
cachedir: .pytest_cache
rootdir: /home/runner/work/ppafm/ppafm
plugins: cov-4.1.0
/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/coverage/report_core.py:[11](https://github.com/Probe-Particle/ppafm/actions/runs/6773029204/job/18406914962?pr=225#step:5:12)5: CoverageWarning: Couldn't parse '/home/runner/work/ppafm/ppafm/_opt_hostedtoolcache_Python_3_9_18_x64_lib_python3_9_site_packages_reikna_algorithms_reduce_mako': No source for code: '/home/runner/work/ppafm/ppafm/_opt_hostedtoolcache_Python_3_9_18_x64_lib_python3_9_site_packages_reikna_algorithms_reduce_mako'. (couldnt-parse)
  coverage._warn(msg, slug="couldnt-parse")
```

**Comment by NikoOinonen** [comment]
@ProkopHapala The fix is on the main branch. If you merge the main branch into this branch, the tests should pass. @yakutovicha was mentioning about this above:
> $ git checkout 224-add-openmp-acceleration
> $ git merge main

**Comment by ProkopHapala** [comment]
> @ProkopHapala The fix is on the main branch. If you merge the main branch into this branch, the tests should pass. @yakutovicha was mentioning about this above:
> 
> > $ git checkout 224-add-openmp-acceleration
> > $ git merge main

Yes, I did it. Still the tests are failing for some reason (which seems unrelated to my changes in this branch) 
But the ubuntu docker finished fine now.

**Comment by NikoOinonen** [comment]
I don't see the fix on this branch. This line is still the old one: https://github.com/Probe-Particle/ppafm/blob/916f3afbe6c5c4b38a2ee2cce46cb188223c79bd/.github/workflows/ci.yml#L24
whereas on the main branch it's this: https://github.com/Probe-Particle/ppafm/blob/9f009aec25d8d895f4168f061501211a37a9dd1c/.github/workflows/ci.yml#L24
Try the merge again. Maybe you just forgot to push.

**Comment by NikoOinonen** [comment]
Or maybe you have an old version of the main branch. I think you need to first checkout and pull the main branch before merging it to this branch.

**Comment by ProkopHapala** [comment]
> checkout and pull the main branch before merging it to this branch.

yeh, I think this was the problem

**Comment by ProkopHapala** [comment]
Now it works fine. Thanks @NikoOinonen 

Before we merge it with main branch it would be good to have some option to switch off the OpenMP.
There are three places:

`CPPFLAGS= -fPIC -std=c++11 -O2 -mtune=native -fopenmp`
in [Makefile](https://github.com/Probe-Particle/ppafm/blob/9d8c9aa98705cfcd9e58f46a4d965777b96bae09/ppafm/cpp/Makefile#L4C1-L4C54)

`#include <omp.h>`
in [ProbeParticle.cpp](https://github.com/Probe-Particle/ppafm/blob/9d8c9aa98705cfcd9e58f46a4d965777b96bae09/ppafm/cpp/ProbeParticle.cpp#L11C1-L11C17)

```
if bOpenMP:
     fzs, PPpos = relaxedScan3D(xTips, yTips, zTips, trj=trj, bF3d=PPU.params["tiltedScan"])
else:
     fzs, PPpos = relaxedScan3D_omp(xTips, yTips, zTips, trj=trj, bF3d=PPU.params["tiltedScan"])
```
in [HighLevel.py](https://github.com/Probe-Particle/ppafm/blob/9d8c9aa98705cfcd9e58f46a4d965777b96bae09/ppafm/HighLevel.py#L162)

**Comment by NikoOinonen** [comment]
I went ahead and fixed it to work also on Windows.

**Comment by NikoOinonen** [comment]
> Before we merge it with main branch it would be good to have some option to switch off the OpenMP.

Is this necessary? As far as I can tell, you can control the number of threads with the `OMP_NUM_THREADS` variable, so you could set it to 1 to run single threaded, and then it's the same as before?

**Comment by ProkopHapala** [comment]
> As far as I can tell, you can control the number of threads with the `OMP_NUM_THREADS` variable, so you could set it to 1 to run single threaded, and then it's the same as before?

perhaps it is not necessary. I'm just not completely sure if
 
* every potential user has OpenMP library (perhaps yes?)
* I did not test it troughfully. Maybe it would be good to check if OMP paralelized function gives the same results as original serial function (perhaps yes)

**Comment by ProkopHapala** [comment]
Another thing:

when using OpenMP paralelization, even on CPU the most time-consuming part become 
* 1 save & load .xsf files
   * Perhaps it would make sense save .npy by default
   * or even make some script which does not save temporary file
* plotting of images with matplotlib

**Comment by ondrejkrejci** [comment]
@ProkopHapala - Please add the documentation to wiki.

**Review by NikoOinonen — APPROVED** [review]
@ProkopHapala The code is good, just make sure to add the documentation as well when you merge.

**Comment by ProkopHapala** [comment]
> @ProkopHapala The code is good, just make sure to add the documentation as well when you merge.

OK, I did Here
https://github.com/Probe-Particle/ppafm/wiki/Install-ppafm#openmp

**Comment by ondrejkrejci** [comment]
I have went through the Wiki text, and added a sentence about setting the number of cores.

**Comment by ProkopHapala** [comment]
@yakutovicha  What does this mean ?

Some checks were not successful
codecov/project — 46.46% (-0.48%) compared to c262867
?

**Comment by yakutovicha** [comment]
> Some checks were not successful
> codecov/project — 46.46% (-0.48%) compared to [c262867](https://github.com/Probe-Particle/ppafm/commit/c262867f7d829528f476457478a24dcc3dea97e6)

Literally what it says - you added a few lines that are not executed during tests, so the coverage has decreased in comparison to the `main` branch. However, as we discussed with @NikoOinonen - we should disable failure because of this. It is too strict at the moment.

**Comment by yakutovicha** [comment]
You can go ahead and merge the PR. We will later configure `codecov` not to fail due to lower coverage.

**Comment by yakutovicha** [comment]
I guess I've just set the threshold to 2%, @ProkopHapala could you try to push something small here? Hopefully, this should pass now.

**Comment by NikoOinonen** [comment]
It's passing on the main branch so should be fine now.

**Pull request merged**
